import { reactive } from "vue";

export const tableData = reactive([
    { switch: true, title: "Wonderwall", description: "4:18" },
    { switch: false, title: "Don't Look Back in Anger", description: "4:48" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne SupernovaChampagne SupernovaChampagne SupernovaChampagne SupernovaChampagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
    { switch: false, title: "Champagne Supernova", description: "7:27" },
]);